title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://proskurekov.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  proskurekov

# Build settings
#theme: minima
remote_theme: riggraz/no-style-please


theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page


sass:
  style: 'compressed'

plugins:
  - jekyll-feed
